import { PrismaClient } from "@/generated/prisma/client"

export async function seedShop(prisma: PrismaClient) {
  const shopsData: string[] = [
    "agro jaya",
    "agribisnis",
    "anugrah",
    "anugrah tani",
    "bawang tani",
    "berkah tani",
    "bina tani",
    "bintang mj",
    "bsd tani",
    "cikeris tani",
    "damai tani",
    "energi tani",
    "ghiross pameungpeuk",
    "haura tani",
    "harapan jaya",
    "hr tani",
    "hr tani cianjur",
    "hrj",
    "hsn",
    "ihsan tani",
    "ikhsan tani",
    "irsyad tani",
    "jasa sepuh",
    "jaya laksana",
    "jaya tani",
    "karunia tani cilawu",
    "karya tani",
    "kurnia tani",
    "lestari tani",
    "marga ikhtiar tani",
    "marga tani",
    "mekar tani",
    "mitra tani",
    "mukti tani",
    "mulya ikhtiar",
    "mulya tani",
    "pd murangkalih",
    "pd nursyamsi",
    "pd sawargi tani",
    "pd sehati",
    "pd sehati cisurupan",
    "putra dsp cisurupan",
    "putra tani",
    "rahma tani",
    "saprodi",
    "sbh tani",
    "sehati tani",
    "sinar mulya",
    "sohor tani",
    "sumber tani",
    "sumber tani makmur",
    "tampomas",
    "tani kita",
    "tani saputra",
    "trisno",
    "umi irsayd",
    "wasilah",
    "wasilah tani",
    "yana tani",
  ]

  const shops = await prisma.shop.createMany({
    data: shopsData.map((shop) => ({ name: shop })),
    skipDuplicates: true,
  })

  console.log(`${shops.count} Shops inserted ✅`)
}
